/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f103xx.h"

void delay(void)
{
    for (uint32_t i=0;i < 500000/2; i++);
}

int main(void)
{
    GPIO_Handle_t GpioLED;

    GpioLED.pGPIOx = GPIOC;
    GpioLED.GPIO_PinConfig.GPIO_PinNumber = 13;
    GpioLED.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT_OD;
    GpioLED.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_10MHZ;

    ErrState retInit;
    retInit = GPIO_Init(&GpioLED);

    /* Loop forever */
    while(1)
    {
        GPIO_ToggleOutputPin(GPIOC, 13);
        delay();
    }
}
